t = int(input())
for T in range(t):
    n = int(input())
    n1 = int(input())
    total = pow(10, n)
    print(total * 2 + n1)
    n3 = int(input())
    print(total - n3)
    n5 = int(input())
    print(total - n5)
    v = int(input()) 
